library(shiny)
library(shinyjs)
library(shinythemes)
library(ggplot2)
library(scales)
library(dplyr)
library(Matrix)
library(matrixStats)
library(tidyr)
library(readr)
library(psych)
library(pheatmap)
library(RColorBrewer)
library(progress)
library(grid)
library(impute)
library(shinycssloaders)
library(rmarkdown)
library(DT)
library(limma)
# library(STRINGdb)
library(qvalue)
library(ROCR)
library(plotROC)


# ------------------------------------------------------------
source("fun-auxFunctions_ModifySource.R")
source("fun-boxplotEssentiality_ModifySource.R")
source("fun-boxplotMutation_ModifySource.R")
source("fun-F_EG_Selection_ModifySource.R")
source("fun-F_filter_tr_gn_and_getGN_ModifySource.R")
source("fun-F_get_exp_genes_ModifySource.R")
source("fun-F_predictBiomarkers_trans_ModifySource.R")
source("fun-getPairs_tr2_ModifySource.R")
source("fun-ggmatplot_ModifySource.R")
source("fun-multiplot_ModifySource.R")